#!/bin/bash
export PYENV_ROOT="$HOME/.pyenv"
# export PYENV_DEBUG=0
export PYENV_FORCE=1
if [[ ! -d $PYENV_ROOT ]] || [[ 1 -eq $PYENV_FORCE ]]; then
    git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT
    git clone https://github.com/pyenv/pyenv-virtualenv.git \
        $PYENV_ROOT/plugins/pyenv-virtualenv
    git clone https://github.com/pyenv/pyenv-virtualenvwrapper.git \
        $PYENV_ROOT/plugins/pyenv-virtualenvwrapper
    git clone https://github.com/yyuu/pyenv-pip-rehash.git \
        $PYENV_ROOT/plugins/pyenv-pip-rehash
    git clone https://github.com/pyenv/pyenv-update.git \
        $PYENV_ROOT/plugins/pyenv-update
    git clone git://github.com/pyenv/pyenv-doctor.git \
        $($PYENV_ROOT)/plugins/pyenv-doctor
    git clone https://github.com/pyenv/pyenv-ccache.git \
        $PYENV_ROOT/plugins/pyenv-ccache
    git clone https://github.com/jawshooah/pyenv-default-packages.git \
        $PYENV_ROOT/plugins/pyenv-default-packages
    git clone https://github.com/massongit/pyenv-pip-update \
        $PYENV_ROOT/plugins/pyenv-pip-update
fi

export PATH="/home/tom/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
dppath=$PYENV_ROOT/default-packages
tppath=/tmp/shit_$RANDOM
cat > $tppath <<EOF
rich
ipython
psutil
jedi
wheel
urllib3
requests
pkg_resources
json5
dateutil
EOF

[[ -e $dppath ]] && (diff $tppath $dppath -q || \
    (mv $dppath ${dppath}-$(date -u +%FT%T%Z) && mv $tppath $dppath)) || \
    mv $tppath $dppath
