#!/usr/bin/zsh
# echo .zshenv
# lifted from:
# https://github.com/agkozak/dotfiles



if [[ -z $ENV ]] && [[ -n $PATH ]]; then
  case $- in
    *l*) ;;
    *) [[ -f ${HOME}/.profile ]] && source ${HOME}/.profile ;;
  esac
fi
# source ~/.zshenv.local {{{1

[[ -f ${HOME}/.zshenv.local ]] && source ${HOME}/.zshenv.local
# # vim: ai:fdm=marker:ts=2:et:sts=2:sw=2
