#!/usr/bin/zsh
# echo .zshenv
# lifted from:
# https://github.com/agkozak/dotfiles

# Benchmarks {{{1
echo "---- zshenv ----"
typeset -F SECONDS=0

# }}}1

# if ~/.profile has not been loaded and /etc/zsh/zshenv has {{{1

if [[ -z $ENV ]] && [[ -n $PATH ]]; then
  case $- in
    *l*) ;;
    *) [[ -f ${HOME}/.profile ]] && source ${HOME}/.profile ;;
  esac
fi

# }}}1


# # Add snap binary and desktop directories to environment {{{1
#
# if whence -w snap &> /dev/null && [[ -f /etc/profile.d/apps-bin-path.sh ]]; then
#   if [[ ! $PATH == */snap/bin* ]] || [[ ! $XDG_DATA_DIRS == */snapd/* ]]; then
#     emulate sh
#     source /etc/profile.d/apps-bin-path.sh
#     emulate zsh
#   fi
# fi

# }}}1

# source ~/.zshenv.local {{{1

[[ -f ${HOME}/.zshenv.local ]] && source ${HOME}/.zshenv.local

# }}}1

# Benchmarks {{{1

typeset -g TOM_ZSHENV_BENCHMARK=${$(( SECONDS * 1000))%.*}

# }}}1
[[ -z "$TMUX" ]] && export STARTTMUX=1
#   export CCDIR=$PWD
#   echo $CCDIR > /tmp/ccdir
  
#   cd /tmp
#   tmux -vv
#   exit $?
# elif [[ "/tmp" == "$PWD" ]]; then
#   cd $HOME
# fi
# # [[ -n "$STARTTMUX" ]] && tmux
# # vim: ai:fdm=marker:ts=2:et:sts=2:sw=2
