#!/usr/bin/bash
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[[ -f ~/.Xmodmap  ]] && xmodmap ~/.Xmodmap
[[ -f ~/.profile ]] && source ~/.profile

#  screen resolution set in .xinitrc

case "$(hostnamectl --static)" in
    "betelgeuse")
        bspc monitor DP-2 -d 0
        bspc monitor %DP-1.1 -d 1 2 3
        bspc monitor %DP-1.3 -d 4 5 6
        bspc monitor %DP-1.2 -d 7 8 9
        ;;
    "stiller") bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 ;;
esac


xrget() {
    xrdb -query | grep $1 | awk '{print $NF}'
}
bspc config border_width         4
#bspc config auto_alternate              true
bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# bspc config normal_border_color $(xrget color13)
# bspc config focused_border_color $(xrget color5)
# bspc config active_border_color $(xrget color10)
# bspc config presel_feedback_color $(xrget color9)
bspc config normal_border_color "#32302f"
bspc config active_border_color "#b16286"
bspc config focused_border_color "#d3869b"
bspc config presel_feedback_color "#ff458588"
# bspc config active_border_color "#6272a4"
# bspc config focused_border_color "#8be9fd"
bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

for r in $(bspc rule --list | awk '{print $1}'); do
    bspc rule --remove $r
done

pgrep -f scratchpad && pkill -f scratchpad
bspc rule -a 'scratchpad:*' state=fullscreen sticky=on hidden=on \
    follow=on

bspc rule -a Spotify desktop='^1' follow=on
# bspc rule -a Signal desktop='^2' follow=on
bspc rule -a Slack desktop='^4' follow=on
# bspc rule -a Telegram desktop='^9' follow=on
bspc rule -a Chromium desktop='^7'
bspc rule -a Firefox desktop='^7'
bspc rule -a Brave desktop='^8'
bspc rule -a Notion desktop='^6'
bspc rule -a googledocs-nativefier-e89b69 desktop='^5'
# bspc rule -a mplayer2 state=floating
bspc rule -a xeyes state=floating
bspc rule -a nitrogen state=floating
# bspc rule -a nitrogen state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad locked=on sticky=on state=floating hidden=on
bspc rule -a newsboat desktop='^3' follow=on state=pseudo_tiled
bspc rule -a Dragon-drag-and-drop locked=on sticky=on 
bspc rule --add Xscreensaver-demo:xscreensaver-demo state=floating
bspc rule --add vlc:* state=floating

# googledocs-nativefier-e89b69
kil sxhkd
kil cbatticon
# kil blueberry-tray
pgrep xcape && killall xcape
xcape -t 250 -e 'Shift_L=F12' >/dev/null 2>&1 &
xcape -t 250 -e 'Shift_R=F10' >/dev/null 2>&1 &
xcape -t 250  -e 'Super_L=Super_L|d' >/dev/null 2>&1 &
xcape -t 250 -e 'Super_R=Super_R|r' >/dev/null 2>&1 &

[[ -f ~/.config/nitrogen/bg-saved.cfg ]] && nitrogen --restore || ~/bin/wp

dex -a -v > /tmp/dex.out 2>&1

sudo chown -R tom:tom /sys/class/backlight/intel_backlight/*
# libinput-gestures-setup restart
# pgrep xscreensaver && pkill xscreensaver
xscreensaver -nosplash >/dev/null 2>&1 & disown
#
xset 180 120
# xss-lock -n dim-screen.sh -- ~/bin/lock &

sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $sid)" ] \
	&& alacritty -t scratchpad --class scratch,scratchpad -d 81 25\
	& sleep 1 \
	&& sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$sid" > /tmp/scratchID ;

cid=$(wmctrl -lx | grep calc.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $cid)" ] \
	&& alacritty -t calculator --class calc,scratchpad -d 37 25 -e bash -c "calc -d" \
	& sleep 1 \
	&& cid=$(wmctrl -lx | grep calc.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$cid" > /tmp/calcID ;


bspc config window_gap 40
bspc config top_padding 16
bspc config bottom_padding 24
bspc config left_padding -32
bspc config right_padding -32 
